#dynamic_title = true

[colors.primary]
background = "#07222e"
bright_foreground = "#eaeaea"
dim_foreground = "#828482"
foreground = "#e2e6f0"

[font]
size = 8

[font.bold]
family = "Terminus"
style = "Bold"

[font.bold_italic]
family = "Terminus"
style = "Bold Italic"

[font.italic]
family = "Terminus"
style = "Italic"

[font.normal]
family = "Terminus"
style = "Regular"

[window]
opacity = 0.9
